### ISSUE TITLE
Add appropriate user experience

### ISSUE THREAD

**Issue by sudeephb** [canonical/hardware-observer-operator#11]
* The charm users should be able to set each of the different sensors/raid controllers monitoring to `on` or `off` as they see fit.
* The charm should be able to automatically enable monitoring for the available controllers/sensors in the beginning.
* If the user enables monitoring for a certain type of sensor/controller, but the required resource/hardware cannot be found, the charm should inform the user (possibly via `blocked` status and a message in `juju status`).

**Comment by jneo8** [comment]
#18
#25
