### ISSUE TITLE
Charm upgrade doesn't update alert rules

### ISSUE THREAD

**Issue by przemeklal** [canonical/hardware-observer-operator#127]
I've upgraded the hardware-observer charm to rev 22 today. Alert rules didn't get updated. For example, this old alert rule is still there:
```
name: IPMISensorStateNotOk
expr: ipmi_generic_sensor_value{juju_application="nova-compute",juju_model="openstack",juju_model_uuid="redacted",state=~"Warning|Critical"}
```
Freshly deployed rev 22 in another juju model created this alert rule correctly:
```
name: IPMISensorStateNotOk
expr: ipmi_generic_sensor_value{juju_application="infra-node",juju_model="maas-infra",juju_model_uuid="redacted",state=~"Warning|Critical",type!~"Entity\\sPresence|Slot/Connector"}
```

**Comment by chanchiwai-ray** [comment]
Can you try removing relation and adding relation to see if it solve the problem? If it does solve the problem, then I think we can try to adding the upgrade event to [COSAgentProvider](https://github.com/canonical/grafana-agent-k8s-operator/blob/3b44d3e96581dbf63eef49ce39017c28a495f67a/lib/charms/grafana_agent/v0/cos_agent.py#L379)

**Comment by przemeklal** [comment]
Removing and re-adding relations with nova-compute and grafana-agent resulted in all units in this env stuck in the blocked state reported in issue #128.

The same alert from the previous charm revisions is still visible in Prometheus, the new one still hasn't appeared but that might be because all units are now blocked.

**Comment by chanchiwai-ray** [comment]
hmm, I guess one of the relation data should be updated `hardware-observer` <--A--> `grafana-agent` <--B--> `prometheus-k8s` because the alert rules are passed via the relation data.

If removing and re-adding A isn't working, maybe B should be re-created. However, I would probably not do it in prod environment, since I am not sure what could break. `juju show-unit` may give you the hints

**Comment by przemeklal** [comment]
This is a production environment and the relation you described as B cannot be recreated just for troubleshooting purposes. Prometheus redeployment is even less acceptable in this env. Besides, all hardware-observer units are now `blocked` as mentioned earlier due to another issue.

**Comment by przemeklal** [comment]
I shared the output of `juju show-unit` for one of the grafana-agent units privately.

**Comment by Pjack** [comment]
It should be an issue in cos-proxy after dig into the issue.

**Comment by Pjack** [comment]
Need to register the refresh event during create [COSAgentProvider](https://github.com/canonical/grafana-agent-k8s-operator/blob/3b44d3e96581dbf63eef49ce39017c28a495f67a/lib/charms/grafana_agent/v0/cos_agent.py#L379)
ex: https://github.com/canonical/postgresql-operator/blob/main/src/charm.py#L145
