### ISSUE TITLE
Default port 10000 overlaps with juju-backup-all

### ISSUE THREAD

**Issue by przemeklal** [canonical/hardware-observer-operator#133]
By default hardware-observer uses port 10000 which overlaps with another Solutions Engineering project https://code.launchpad.net/juju-backup-all. In our deployments, juju-backup-all usually runs on physical machines so almost every time we run into this conflict.

I'm aware of `juju config hardware-observer exporter-port`.

Can the defaults be updated so there's no overlap between these two projects?

**Comment by dashmage** [comment]
This seems simple enough to fix. Is there any preference or can I just pick a random default port which isn't 10000 (say 9000)?

**Comment by Pjack** [comment]
Maybe we can try to allocate a port here.
https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Comment by dashmage** [comment]
> Maybe we can try to allocate a port here. https://github.com/prometheus/prometheus/wiki/Default-port-allocations

10200 looks good, what do you say? Doesn't seem to be taken up by any other default port allocations.
