### ISSUE TITLE
Update status hook not able to start inactive status service.

### ISSUE THREAD

**Issue by jneo8** [canonical/hardware-observer-operator#144]
If charm relate to two grafana-agent applications, the charm will get into blocked status. But after user remove 1 grafana-agent relation, the service will go to inactive because we stop service on relation departed hook and it's not able to recover from update-status, update status only restart failed status service.

**Comment by Pjack** [comment]
Need to set up limit in metadata.yaml
https://juju.is/docs/sdk/metadata-yaml#heading--provides
