### ISSUE TITLE
ops.ErrorStatus is read-only and cannot be set

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/hardware-observer-operator#159]
The [restart_exporter() method](https://github.com/canonical/hardware-observer-operator/blob/a241bd70b79e14020a25ba2606c948d1feb3e9dc/src/charm.py#L145) will return `ops.ErrorStatus("...")` in some situations, and this is [used](https://github.com/canonical/hardware-observer-operator/blob/a241bd70b79e14020a25ba2606c948d1feb3e9dc/src/charm.py#L140) to set the unit status.

However, this doesn't work - Juju will return a `ERROR invalid status "error", expected one of [maintenance blocked waiting active]` error, which ops will turn into a `ModelError`. The charm does end up in an error state, but because setting the status crashed, not because you've explicitly set the error state.

This is caught by the existing unit tests if you run with ops >= 2.10 (because Harness now models the Juju behaviour).

**Comment by tonyandrewmeyer** [comment]
@Pjack #157 works around this issue, but it doesn't actually *fix* it (and it stops you from getting any further improvements in `ops` until this is properly fixed). If you want the Charm to die with an error state, then there are cleaner ways of doing that. I think you probably want some other status though - most likely `BlockedStatus` - unless you are looking for specific error behaviour (like Juju retrying).

**Comment by Pjack** [comment]
Thanks for the remind~ I decide to reopen it and find time to figure out how to enhance it.
