### ISSUE TITLE
Ensure clean-up for func tests

### ISSUE THREAD

**Issue by dashmage** [canonical/hardware-observer-operator#175]
In the `test_config_changed_port` and `test_config_changed_log_level` tests, the [clean-up steps](https://github.com/canonical/hardware-observer-operator/blob/master/tests/functional/test_charm.py#L145)  
```
await app.reset_config(["exporter-port"])
```

may not execute in case of a failure in any of the previous lines of code.

In order to fix this, we would need a cleanup phase where even if an error occurs, the cleanup will happen before the test exits.

**Comment by dashmage** [comment]
The [`addCleanup`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.addCleanup) method could be used for this purpose if we define the `TestCharm` as a [TestCase](https://docs.python.org/3/library/unittest.html#unittest.TestCase).

**Comment by Pjack** [comment]
The code has changed, and it’s unlikely this issue will be addressed in the future. I’ll close the ticket for now, but feel free to reopen it if anyone wants to enhance this part.
