### ISSUE TITLE
for hpe ilo5 the storagecontroller key is called controller

### ISSUE THREAD

**Issue by nishant-dash** [canonical/hardware-observer-operator#177]
I have attached the entire list of sanitized curl commands here : 
[sanitized-curls.txt](https://github.com/canonical/hardware-observer-operator/files/14433534/sanitized-curls.txt)

Essentially, we have
```
/redfish/v1/Systems/1/Storage/DE044000/Controllers/0
```
Notice the `Controllers` instead of `Storagecontrollers`.

Also the heirarchy of the data shows the actual information is one level deeper at `/Controller/0`

**Comment by nishant-dash** [comment]
can confirm rev `69` of the charm is able to read this correctly
```console
May  3 15:06:19 <REDACTED> python3[2504348]: 2024-05-03 15:06:19 INFO Response Time for GET to /redfish/v1/Systems/1/Storage/DE044000/Controllers/0: 0.018857445567846298 seconds.
```

**Comment by chanchiwai-ray** [comment]
Closed by https://github.com/canonical/prometheus-hardware-exporter/pull/71
