### ISSUE TITLE
hardware observer has ERROR 'StorageControllers'

### ISSUE THREAD

**Issue by honghan-wong** [canonical/hardware-observer-operator#222]
We received alerts related to 

`redfish_collector_failed{collector="redfish"} 1.0`
```
Apr 18 04:30:33 infra python3[298134]: 2024-04-18 04:30:33 INFO Getting storage controller data...
Apr 18 04:30:33 infra python3[298134]: 2024-04-18 04:30:33 INFO Attempt 1 of /redfish/v1/
Apr 18 04:30:33 infra python3[298134]: 2024-04-18 04:30:33 INFO Attempt 1 of /redfish/v1/Systems/1/Storage/DE042000
Apr 18 04:30:33 infra python3[298134]: 2024-04-18 04:30:33 INFO Response Time for GET to /redfish/v1/Systems/1/Storage/DE042000: 0.010007815901190042 seconds.
Apr 18 04:30:33 infra python3[298134]: 2024-04-18 04:30:33 ERROR 'StorageControllers'
```

There are some request in middle but not related to Storage Controller.
The Error stopped and no additional information is provided.
Is there any information we can provide to resolve this?

**Comment by facundofc** [comment]
Possibly duplicate of [#69 on the prometheus-harwdare-observer](https://github.com/canonical/prometheus-hardware-exporter/issues/69) repo.

**Comment by dashmage** [comment]
Also quite similar to #115 and #177. This is potentially due to differing API paths for different hardware while querying for storage controller data from redfish

**Comment by honghan-wong** [comment]
no ERROR seens after updated to rev 69, which including patch https://github.com/canonical/prometheus-hardware-exporter/pull/71
