### ISSUE TITLE
Deprecate the usage of `/etc/hardware-exporter-config.yaml`

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/hardware-observer-operator#230]
The [prometheus-hardware-exporter](https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/__main__.py#L33) accept command line flags instead of config file. We should directly render the config file as the command line flag in the [hardware-exporter.service.j2](https://github.com/canonical/hardware-observer-operator/blob/master/templates/hardware-exporter.service.j2). This will reduce our effort to maintain two config files.

**Comment by aieri** [comment]
@chanchiwai-ray I suspect that most if not all changes would end up in the config file, and not in the systemd service (meaning that we already kind of are maintaining only one of those two). Why would it be better to move the config values to CLI options?

**Comment by chanchiwai-ray** [comment]
This was only to make the charm code cleaner: we don't need to explicitly render config -> render service -> start service when installing the exporter, but that's more of a refactoring

**Comment by Pjack** [comment]
I'm afraid that we won't handle this one (priority is very low). I will close this request
