### ISSUE TITLE
Redfish query take too long

### ISSUE THREAD

**Issue by jneo8** [canonical/hardware-observer-operator#282]
Reported by @przemeklal

The redfish query take more than 2 minutes to finish and cause the grafana-agent scrape timeout.

The possible option we can have is to:

1. Cache the redfish metrics
2. Provide a global configuration to disable the redfish

**Comment by przemeklal** [comment]
It would be good to have both options - caching makes sense because redfish often takes more than 1m which causes problems for grafana-agent.

Also, on many systems Redfish implementation often has vendor-specific features that often break the collector so it would be good to have the option to disable it.

**Comment by err404r** [comment]
+1 for caching, it should be there. Also cache age must be exported to prometheus. Together with additional alert rule. To notify us that cache is too old.

**Comment by aieri** [comment]
instead of adding a new config option we could perhaps simply make empty redfish credentials mean "collector disabled"

**Comment by aieri** [comment]
tentative proposal:
* deploy hardware observer with default config (i.e. no redfish credentials) on hardware that supports redfish:
  * prometheus-hardware-exporter disables the redfish collector
  * hardware-observer goes to active/idle with message "redfish detected; provide credentials to enable the collector"
  * no alerts and no redfish metrics are produced
* if the `redfish-username` charm option is provided, enable the collector and the alerting rule
