### ISSUE TITLE
Honor juju-proxies and allow uploading of smartctl exporter binary as resource

### ISSUE THREAD

**Issue by marcusboden** [canonical/hardware-observer-operator#304]
The charm currently pulls the smartctl exporter binary from github. It would be helpful if we can manually upload it as a resource like the other debs, in case the charm runs in an airgapped environment.

Additionally, the charm should honor the juju-proxy settings if they are set.

**Comment by aieri** [comment]
closing as the smartctl_exporter is now snapped and will be fetched from the store (or the store proxy)
