### ISSUE TITLE
Failed to communicate with NVIDIA driver. See more details in the logs

### ISSUE THREAD

**Issue by d-kazantsev** [canonical/hardware-observer-operator#362]
I deployed hardware-observer on the node with NVIDIA GPU but it is going to be used in PCI passthrough mode to be attached directly to the VM. When I check hardware-observer status I see this message " Failed to communicate with NVIDIA driver. See more details in the logs"

Logs indicated error in snap.dcgm.dcgm-exporter.service starting:

systemctl status snap.dcgm.dcgm-exporter.service
○ snap.dcgm.dcgm-exporter.service - Service for snap application dcgm.dcgm-exporter
     Loaded: loaded (/etc/systemd/system/snap.dcgm.dcgm-exporter.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2024-12-02 23:09:03 UTC; 1 day 15h ago
   Main PID: 2265007 (code=exited, status=0/SUCCESS)
        CPU: 768ms

Dec 02 23:08:57 ps7-r1-n1 systemd[1]: Started Service for snap application dcgm.dcgm-exporter.
Dec 02 23:08:58 ps7-r1-n1 dcgm.dcgm-exporter[2265007]: time="2024-12-02T23:08:58Z" level=info msg="Starting dcgm-exporter"
Dec 02 23:08:58 ps7-r1-n1 dcgm.dcgm-exporter[2265007]: time="2024-12-02T23:08:58Z" level=info msg="Attemping to connect to remote hostengine at localhost:5555"
Dec 02 23:09:03 ps7-r1-n1 dcgm.dcgm-exporter[2265007]: time="2024-12-02T23:09:03Z" level=error msg="Encountered a failure." stacktrace="goroutine 1 [running]:\nruntime/debug.Stack()\n>
Dec 02 23:09:03 ps7-r1-n1 systemd[1]: snap.dcgm.dcgm-exporter.service: Deactivated successfully.

journalctl logs dcgm exporter are here: https://pastebin.canonical.com/p/wwWsrcZCtt/ 

Note that NVIDIA driver is blacklisted during the boot time to allow successful pci-passthrough. 

snap list dcgm
Name  Version  Rev  Tracking       Publisher   Notes
dcgm  3.3.8    31   latest/stable  canonical✓  -

Ubuntu Jammy 22.04 

 *-display UNCLAIMED
       description: 3D controller
       product: GA100GL [A30 PCIe]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:a1:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm cap_list
       configuration: latency=0
       resources: iomemory:af00-aeff iomemory:b000-afff memory:b0000000-b0ffffff memory:af000000000-af7ffffffff memory:b0010000000-b0011ffffff memory:b1000000-b11fffff memory:af800000000-affffffffff memory:b0000000000-b000fffffff

**Comment by aieri** [comment]
hi @d-kazantsev the current charm logic installs dcgm if an NVIDIA gpu is found via lshw (see https://github.com/canonical/hardware-observer-operator/blob/174389c7513c8bb110c05da54bc9d680935133b8/src/hw_tools.py#L671). I'm thinking we could make the logic more stringent by adding a "...and the driver isn't blacklisted" clause.

Could you please verify a couple of things:
* `lshw -c display` still shows the vendor being NVIDIA
* you blacklisted the driver by adding a `blacklist nvidia*` string to `/etc/modprobe.conf` or another conffile under `/etc/modprobe.d/`

thanks

**Comment by aieri** [comment]
@d-kazantsev I have created a draft PR with a possible fix but I would like to ensure it would solve your specific use case before completing it and merging it. Please take a look

**Comment by aieri** [comment]
I see, then my current proposal would not be sufficient: if you're modifying the kernel parameters via grub config I also need to look into `/proc/cmdline`

**Comment by aieri** [comment]
@d-kazantsev this is now fixed and available in edge (rev 145). Note that unfortunately at the moment we are not handling automating the cleanup of the current stable version (rev 128) on a nvidia-gpu-enabled server configured to do pci passthrough: if you are currently running rev 128 and upgrade to rev 145 you will need to manually remove the DCGM snap and unload the driver module. Upgrades from earlier revisions or deployments of rev 145 do not suffer from this issue.
