### ISSUE TITLE
Smartctl dashboard incorrectly reports "missing devices"

### ISSUE THREAD

**Issue by przemeklal** [canonical/hardware-observer-operator#368]
latest/stable rev 84

I'm not sure how to interpret this and what is considered a missing device by the dashboard but the actual cloud and hardware seem to be completely fine.
![image](https://github.com/user-attachments/assets/75eba29c-9337-42e4-98ca-75b9b288a8f6)

**Comment by przemeklal** [comment]
This might be related to https://github.com/canonical/hardware-observer-operator/issues/357

**Comment by Deezzir** [comment]
This is related to #353 as well and will be refined shortly.

Also, duplicate to #283
