### ISSUE TITLE
Issue with sas2ircu resource

### ISSUE THREAD

**Issue by dashmage** [canonical/hardware-observer-operator#52]
While attaching the `sas2ircu` resource downloaded from the location mentioned in the resources page (https://docs.broadcom.com/docs/12351730), the binary doesn't work.

```sh
ubuntu@gurley:~$ curl localhost:10000 | grep ^sas2ircu
sas2ircu_command_success 0.0

ubuntu@gurley:~$ journalctl -xeu hardware-exporter.service
Aug 01 13:34:05 gurley python3[3514477]: /bin/sh: 1: sas2ircu: Exec format error
Aug 01 13:34:05 gurley python3[3506754]: 2023-08-01 13:34:05 ERROR Command 'sas2ircu list' returned non-zero exit status 126.
Aug 01 13:34:05 gurley python3[3506754]: 2023-08-01 13:34:05 ERROR Command 'sas2ircu list' returned non-zero exit status 126.
Aug 01 13:34:05 gurley python3[3506754]: 2023-08-01 13:34:05 ERROR Failed to get LSI SAS-2 controller information using sas2ircu


ubuntu@gurley:~$ sudo sas2ircu list
/usr/sbin/sas2ircu: 1: ELFlp@: not found
/usr/sbin/sas2ircu: 1: @8@: not found
/usr/sbin/sas2ircu: 2: Syntax error: ")" unexpected

```

The symlink also seems to be pointing to the resource in the location `/var/lib/juju` rather than in `/opt/MegaRAID` where the symlinks for the other resources (`perccli`, `storcli`) are usually pointing. This is the case for both `sas2ircu` and `sas3ircu`.

```
ubuntu@prunus:~$ ls -l /usr/sbin/sas2ircu 
lrwxrwxrwx 1 root root 65 Aug  1 14:14 /usr/sbin/sas2ircu -> /var/lib/juju/agents/unit-hardware-observer-35/resources/sas2ircu

ubuntu@bomberto:~$ ls -l /usr/sbin/sas3ircu 
lrwxrwxrwx 1 root root 65 Aug  1 17:19 /usr/sbin/sas3ircu -> /var/lib/juju/agents/unit-hardware-observer-36/resources/sas3ircu
```

**Comment by jneo8** [comment]
For the softlink part, it's the normal case.
Because user will upload the binary file instead of deb, we don't have to put it under `/opt/MegaRAID`. Also sas2ircu & sas3ircu are tool for SAS device, not RAID.

**Comment by dashmage** [comment]
> For the softlink part, it's the normal case. Because user will upload the binary file instead of deb, we don't have to put it under `/opt/MegaRAID`. Also sas2ircu & sas3ircu are tool for SAS device, not RAID.

Understood. But I think it's good to mention in the documentation somewhere about where the resource (and the binary symlink) will be located after attaching to the charm. This will help for debugging later on. 

And for the other RAID related tools apart from storcli, ie, perccli, sas{2,3}ircu -- they should not be under `/opt/MegaRAID` since only storcli is used for MegaRAID.

**Comment by dashmage** [comment]
This issue was caused due to me using the `sas2ircu` binary for the wrong architecture. Upon redoing this with the correct Linux x86-64 binary, I was able to get everything working.
