### ISSUE TITLE
Support arm64 architecture

### ISSUE THREAD

**Issue by przemeklal** [canonical/hardware-observer-operator#58]
We'd like to be able to monitor arm64 servers, as far as I am aware this architecture is not supported at the moment.

**Comment by Pjack** [comment]
Grafana-agent doesn't supported arm64 now. It's a blocker.

**Comment by samuelallan72** [comment]
Note: this is no longer blocked as grafana-agent-k8s now supports arm64.

**Comment by Pjack** [comment]
Supported in

#303 
#308 
#312
