### ISSUE TITLE
Install strategy to cover perccli rpm resource file.

### ISSUE THREAD

**Issue by jneo8** [canonical/hardware-observer-operator#67]
Currently the InstallStrategy for PercCLI require user to transform the rpm file to deb file manually. However this make the chekcsum logic not possible to implementation because the hash will be different every time.

We can change the process to allow user to upload rpm file, check sum, and  do the transform inside the charm.

**Comment by Pjack** [comment]
This link is used in hw-health.
https://dl.dell.com/FOLDER07576010M/1/PERCCLI_7.1623.00_A11_Linux.tar.gz
It contains deb package that ubuntu can install it directly. 

I think we use replace the link in hardware-observer to this one Or even this newer version
https://www.dell.com/support/home/zh-tw/drivers/driversdetails?driverid=36g6n
PERCCLI_7.1910.00_A12_Linux.tar.gz

**Comment by jneo8** [comment]
The newest version can be found in here: https://www.dell.com/support/search/zh-tw#q=%22LINUX%20PERCCLI%20Utility%22&sort=date%20descending&f:iuxType=[Drivers%20%26%20Downloads]

Instead of point to specific version, maybe we can point to this search page and limit the version by https://github.com/canonical/prometheus-hardware-exporter/issues/31

**Comment by jneo8** [comment]
Close by #77
