### ISSUE TITLE
Include support for scaphandre

### ISSUE THREAD

**Issue by aieri** [canonical/hardware-observer-operator#82]
From the official docs:
> Scaphandre [skafɑ̃dʁ] is a metrology agent dedicated to electrical [power](https://en.wikipedia.org/wiki/Electric_power) consumption metrics. The goal of the project is to permit to any company or individual to measure the power consumption of its tech services and get this data in a convenient form, sending it through any monitoring or data analysis toolchain.

I think Scaphandre could fit well into this charm, and would let cloud operators estimate the power consumption of their estate and how it varies depending on the workload.

An initial snap is also available at https://launchpad.net/~lool/+snap/scaphandre-snap

**Comment by dashmage** [comment]
Here's a link to the upstream project for anyone else.
https://github.com/hubblo-org/scaphandre

**Comment by Pjack** [comment]
I haven't received any additional requirements for this task. I've decided to close it for now, but if someone brings up the same requirement in the future, we can revisit it then.

**Comment by tytus-kurek** [comment]
@Pjack having Scaphandre integrated into our tooling would be very useful and would go in line with our direction for power consumption optimisation for carbon neutrality. It has been on my list of things to research for a while anyway. If we don't think this is the right place for it, let's find a better one. But if it is, let's add it to a backlog, please.
