### ISSUE TITLE
Have the incorrect redfish credentials status surface in the juju status

### ISSUE THREAD

**Issue by aieri** [canonical/hardware-observer-operator#84]
hardware-observer currently produces an alert if the provided redfish credentials are incorrect. However, this is not an alert in the sense of anything being wrong with the hardware, but rather a charm configuration issue. We should find a good way to have this status be visible in juju status (in addition to continuing to produce alerts in alertmanager).

**Comment by Pjack** [comment]
The charm will enter "blocked" state if the credential is incorrect now. relative PR:
https://github.com/canonical/hardware-observer-operator/pull/182
https://github.com/canonical/hardware-observer-operator/pull/192
I think we are good with this issue. I will close it but welcome to reopen it if any concern.
