### ISSUE TITLE
Wrong default prometheus port in tutorial

### ISSUE THREAD

**Issue by valexby** [canonical/hardware-observer-operator#89]
Hey,

In the [main tutorial](https://charmhub.io/hardware-observer/docs/tutorial) documentation say's that "machine hosting ... endpoint http://localhost:10000", and in the example below one 0 is missing\
```
juju ssh hardware-observer/0 curl localhost:1000
```
There should be `10000` too.

**Comment by chanchiwai-ray** [comment]
it's now fixed: https://charmhub.io/hardware-observer/docs/tutorial
