### ISSUE TITLE
Support for smart array

### ISSUE THREAD

**Issue by nishant-dash** [canonical/hardware-observer-operator#90]
Since hardware observer right now (edge, revision 15) looks at `lshw` to get raid information, this does not work with smart arrays like on `HPE ProLiant DL380 Gen10` which do not show in lshw but they do show in ilorest

```console
$ ilorest ilorest storagecontroller
iLOrest : RESTful Interface Tool version 4.2.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Controllers:
[0]: Slot 0 - HPE Smart Array P816i-a SR Gen10
```

**Comment by aieri** [comment]
Interesting... does the array at least show up in lspci?

**Comment by aieri** [comment]
@nishant-dash I would like to keep the hardware detection routine independent of external resources. Is there really no other way to detect the presence of a smart array? Maybe via the `/sys` filesystem, `dmidecode`, `lspci`, or even IPMI commands

**Comment by nishant-dash** [comment]
Hi @aieri 
I looked into `dmidecode`, and I can find it under `dmidecode -t 203` since it shows up with type 203 which means its OEM specific. 
I also found it under `/sys/devices/pci.../.../..` or perhaps the easiest and quickest to get format would be from
```sh
hwinfo --storage
```

**Comment by aieri** [comment]
Thank you, we can work with that. Does `hwinfo --storage-ctrl` also report its presence?

**Comment by nishant-dash** [comment]
it does, although I see the exact same output with `hwinfo --storage-ctrl` as I do with `--storage`

**Comment by nishant-dash** [comment]
also I see almost the same output (but  less info) with `lshw -storage`
