### ISSUE TITLE
More useful juju message when required relations are missing

### ISSUE THREAD

**Issue by facundofc** [canonical/hardware-observer-operator#92]
Deployed `hardware-observer` and related it with the principal unit, but missed the relation with the `grafana-agent`. The observer unit went into the `blocked` state with this message:

```
Exporter is not running
```

The message could be more useful mentioning that the required `cos-agent` relation is missing.

**Comment by chanchiwai-ray** [comment]
We do have [checks](https://github.com/canonical/hardware-observer-operator/blob/master/src/charm.py#L85) to see if `cos-agent` is missing on every update status. Are you sure that `cos-agent` relation is missing in your example?
