### ISSUE TITLE
The auto-recover life-cycle when strategy fail to install.

### ISSUE THREAD

**Issue by jneo8** [canonical/hardware-observer-operator#96]
Currently there is no way to auto-recovery when the IPMIStretegy fail to install because of the any issue.

---

## Update 2024/04/01

Currently, the list of strategies need to be installed is generated when

- The install hook fire
- (Dynamically) When update_status/upgrade hooks fire, the list will be generate in real-time for some condition checks.

Some of the hardware verifier return result are not stable due to networking or other issues. This somehow cause the problem report on #202 .

**Comment by jneo8** [comment]
We decide to use action instead of auto-recovery.

**Comment by Pjack** [comment]
Could we have a clear description of this feature? to rescan the available collector and generate configuration file?
